[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "A maze generator package for the 42 curriculum"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen*"]